# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'indexPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_indexPage(object):
    def setupUi(self, indexPage):
        indexPage.setObjectName("indexPage")
        indexPage.resize(512, 445)
        self.verticalLayout = QtWidgets.QVBoxLayout(indexPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLayout = QtWidgets.QHBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        spacerItem = QtWidgets.QSpacerItem(68, 60, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titleLayout.addItem(spacerItem)
        self.label_income = QtWidgets.QLabel(indexPage)
        self.label_income.setObjectName("label_income")
        self.titleLayout.addWidget(self.label_income)
        spacerItem1 = QtWidgets.QSpacerItem(69, 60, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titleLayout.addItem(spacerItem1)
        self.pushButton_account = QtWidgets.QPushButton(indexPage)
        self.pushButton_account.setObjectName("pushButton_account")
        self.titleLayout.addWidget(self.pushButton_account)
        spacerItem2 = QtWidgets.QSpacerItem(68, 60, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titleLayout.addItem(spacerItem2)
        self.label_expense = QtWidgets.QLabel(indexPage)
        self.label_expense.setObjectName("label_expense")
        self.titleLayout.addWidget(self.label_expense)
        spacerItem3 = QtWidgets.QSpacerItem(69, 60, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titleLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.titleLayout)
        self.timeAxisLayout = QtWidgets.QVBoxLayout()
        self.timeAxisLayout.setObjectName("timeAxisLayout")
        self.verticalLayout.addLayout(self.timeAxisLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)

        self.retranslateUi(indexPage)
        QtCore.QMetaObject.connectSlotsByName(indexPage)

    def retranslateUi(self, indexPage):
        _translate = QtCore.QCoreApplication.translate
        indexPage.setWindowTitle(_translate("indexPage", "Frame"))
        self.label_income.setText(_translate("indexPage", "收入"))
        self.pushButton_account.setText(_translate("indexPage", "记一笔"))
        self.label_expense.setText(_translate("indexPage", "支出"))
